
server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:mysql://localhost/0928?rewriteBatchedStatements=true&useServerPrepStmts=false&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: root

  liquibase:
  enabled: true
  change-log: classpath:liquibase/master.xml

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
